import AppKit
import iClipCore

@MainActor
public enum PasteboardBridge {
    public static func read(from pasteboard: NSPasteboard) -> ClipboardEntry? {
        let blocked = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !blocked.contains(where: { pasteboard.types?.contains(NSPasteboard.PasteboardType($0)) == true }) else { return nil }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipboardEntry(text: paths.joined(separator: "\n"), kind: .files, filePaths: paths)
        }
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            guard !data.isEmpty, data.count <= 25 * 1024 * 1024 else { return nil }
            return ClipboardEntry(text: "图片", kind: .image, imageData: data)
        }
        if let text = pasteboard.string(forType: .string), !text.isEmpty, text.utf8.count <= 1_048_576 {
            return ClipboardEntry(text: text)
        }
        return nil
    }

    @discardableResult
    public static func write(_ entry: ClipboardEntry, to pasteboard: NSPasteboard) -> Bool {
        // Prepare and validate before clearing the user's current clipboard.
        switch entry.kind {
        case .text:
            pasteboard.clearContents()
            return pasteboard.setString(entry.text, forType: .string)
        case .files:
            guard !entry.filePaths.isEmpty, entry.filePaths.allSatisfy({ $0.hasPrefix("/") }) else { return false }
            let urls = entry.filePaths.map { NSURL(fileURLWithPath: $0) }
            pasteboard.clearContents()
            return pasteboard.writeObjects(urls)
        case .image:
            guard let data = entry.imageData, !data.isEmpty else { return false }
            let pngSignature: [UInt8] = [137, 80, 78, 71, 13, 10, 26, 10]
            let type: NSPasteboard.PasteboardType = data.starts(with: pngSignature) ? .png : .tiff
            pasteboard.clearContents()
            return pasteboard.setData(data, forType: type)
        }
    }
}
